//
// Created by trashpanda on 26.05.23.
//

#ifndef PIC_AEM_PROJEKT_ACHIEVEMENTLISTWIDGET_H
#define PIC_AEM_PROJEKT_ACHIEVEMENTLISTWIDGET_H


class AchievementListWidget {

};


#endif //PIC_AEM_PROJEKT_ACHIEVEMENTLISTWIDGET_H
